### ISSUE TITLE
external.conf: No such file or directory

### ISSUE THREAD

**Issue by mrskuvare** [ravlaska/piprse#1]
Hi there,
I get the following

`sed: can't read /home/USER/piprse/pihole_vpn/scripts/external.conf: No such file or directory`
`mv: cannot stat '/home/USER/piprse/pihole_vpn/scripts/external.conf': No such file or directory`

What went wrong?

**Comment by ravlaska** [comment]
What is the /home/yourusername/piprse folder looks like inside?
It looks like the script can’t copy the pihole_scripts folder from install folder. I’m
Did you download whole install folder from GitHub and place it in one folder with piprse.sh script?

**Comment by mrskuvare** [comment]
Yes, I did a `git clone ...`. But now the second try worked. Maybe the file wasn't in place when it needed?

**Comment by ravlaska** [comment]
Hmm interesting, but glad to hear that now it’s working fine
